version: '2.1'
orbs:
  gradle: circleci/gradle@3.0.0
workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          reports_path: tptpgrpc/build/reports/
          test_results_path: tptpgrpc/build/test-results/
